export const ROUTES = {
  HOME: 'HOME',
  VISITS: 'VISITS',
  WISHLIST: 'WISHLIST',
  BOOKINGS: 'BOOKINGS',
  NOTIFICATIONS: 'NOTIFICATIONS',
  MESSAGES: 'MESSAGES',
  ACCOUNT: 'ACCOUNT',
  PROFILE: 'PROFILE',
  VERIFICATION: 'VERIFICATION',
  ADDRESSES: 'ADDRESSES',
  REFERRALS: 'REFERRALS',
  SUPPORT: 'SUPPORT',
  SETTINGS: 'SETTINGS',
  TERMS: 'TERMS',
  PRIVACY: 'PRIVACY',
  ABOUT: 'ABOUT',
  FEEDBACK: 'FEEDBACK'
} as const;

export type RouteType = keyof typeof ROUTES;
