import { 
  Home, 
  Bed, 
  Building2, 
  Users, 
  Warehouse, 
  Flame, 
  Compass, 
  ShieldCheck, 
  Zap, 
  Waves, 
  Dumbbell
} from 'lucide-react';
import { Property } from './types';

export const CATEGORIES = [
  { id: 'homes', name: 'HOMES', icon: Home, color: 'bg-blue-50 text-blue-600' },
  { id: 'rooms', name: 'ROOMS', icon: Bed, color: 'bg-orange-50 text-orange-600' },
  { id: 'apartments', name: 'APARTMENTS', icon: Building2, color: 'bg-green-50 text-green-600' },
  { id: 'pgs', name: 'PGS', icon: Users, color: 'bg-indigo-50 text-indigo-600' },
  { id: 'villas', name: 'VILLAS', icon: Warehouse, color: 'bg-amber-50 text-amber-600' },
];

export const SIZZLING_DEALS: Property[] = [
  {
    id: '1',
    title: 'Luxury 3BHK Apartment in HSR Layout - Semi Furnished',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=400',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800'
    ],
    tag: 'PREMIUM LISTING',
    details: '3 BHK • 3 Bath • 1,850 sq. ft.',
    description: 'A beautiful, modern studio apartment located in the heart of Sector 45. Perfect for working professionals looking for a stylish and convenient living space.',
    price: 45000,
    originalPrice: 50000,
    discount: '10% off',
    bedrooms: 3,
    furnished: true,
    category: 'apartments',
    location: '2nd Main, Sector 4, HSR Layout, Bangalore',
    rating: 4.8,
    reviewCount: 124,
    maintenanceInfo: 'Inclusive of Maintenance & Electricity',
    badges: ['IMMEDIATE POSSESSION', 'FAMILY ONLY', 'PREMIUM LISTING'],
    offers: [
      'Bank Offer: 10% instant discount on ICICI Bank Credit Cards.',
      'Move-in Bonus: Flat ₹2,000 off on professional packers & movers.'
    ],
    configuration: '3 BHK + 3 Bath',
    size: '1,850 sq. ft.',
    floor: '4th of 12 Floors',
    facing: 'East (Vastu Compliant)',
    amenities: [
      { icon: Waves, label: 'Swimming' },
      { icon: Dumbbell, label: 'Gym' },
      { icon: ShieldCheck, label: '24/7 Security' },
      { icon: Zap, label: 'Power Backup' }
    ],
    owner: {
      name: 'Rahul Deshmukh',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100',
      verified: true,
      activeSince: '2 days'
    }
  },
  {
    id: '2',
    title: 'Penthouse Suite, Indira Nagar',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=400',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800'
    ],
    tag: 'Flat 5000 Off',
    details: 'Private Terrace • Verified',
    description: 'Experience luxury living in this stunning penthouse suite in Indira Nagar. Boasting a massive private terrace, floor-to-ceiling windows, and premium wooden flooring.',
    price: 45000,
    originalPrice: 50000,
    bedrooms: 3,
    furnished: true,
    category: 'apartments',
    location: 'Indira Nagar, Bangalore',
    rating: 4.5,
    reviewCount: 89,
    badges: ['PREMIUM LISTING'],
    offers: ['Bank Offer: 5% off on HDFC'],
    configuration: '3 BHK + 4 Bath',
    size: '2,200 sq. ft.',
    floor: '10th of 10 Floors',
    facing: 'North',
    amenities: [
      { icon: Dumbbell, label: 'Gym' },
      { icon: ShieldCheck, label: 'Security' }
    ],
    owner: {
      name: 'Suresh Kumar',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100',
      verified: true,
      activeSince: '1 week'
    }
  },
];

export const TOP_SELECTIONS = [
  { id: '1', title: 'Working Professionals', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=300' },
  { id: '2', title: 'Student Housing', image: 'https://images.unsplash.com/photo-1555854816-80dc12219bbf?auto=format&fit=crop&q=80&w=300' },
  { id: '3', title: 'Family Suites', image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=300' },
  { id: '4', title: 'Bachelor Pads', image: 'https://images.unsplash.com/photo-1536376074432-bf121770998a?auto=format&fit=crop&q=80&w=300' },
];

export const RECENTLY_VIEWED: Property[] = [
  {
    id: 'r1',
    title: 'Shared PG, Koramangala',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=300',
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1555854816-80dc12219bbf?auto=format&fit=crop&q=80&w=800'
    ],
    details: 'Shared Room • For Students',
    description: 'Affordable and clean shared PG accommodation in Koramangala.',
    price: 8000,
    bedrooms: 1,
    furnished: false,
    category: 'pgs',
    location: 'Koramangala, Bangalore',
    rating: 4.2,
    reviewCount: 45,
    badges: ['STUDENT FRIENDLY'],
    offers: [],
    configuration: 'Shared Room',
    size: '200 sq. ft.',
    floor: '2nd of 4 Floors',
    facing: 'East',
    amenities: [
      { icon: Flame, label: 'WiFi' }
    ],
    owner: {
      name: 'Anita Rao',
      image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100',
      verified: true,
      activeSince: '3 days'
    }
  },
  {
    id: 'r2',
    title: '1BHK, Marathahalli',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=300',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800'
    ],
    details: 'Semi-Furnished • Near IT Park',
    description: 'Spacious 1BHK apartment located conveniently near Marathahalli IT parks.',
    price: 15500,
    bedrooms: 1,
    furnished: true,
    category: 'apartments',
    location: 'Marathahalli, Bangalore',
    rating: 4.0,
    reviewCount: 32,
    badges: ['NEAR IT PARK'],
    offers: [],
    configuration: '1 BHK + 1 Bath',
    size: '650 sq. ft.',
    floor: '1st of 5 Floors',
    facing: 'West',
    amenities: [
      { icon: Compass, label: 'Gym' }
    ],
    owner: {
      name: 'Vikram Singh',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100',
      verified: true,
      activeSince: '5 days'
    }
  },
  {
    id: 'r3',
    title: 'Full House, Whitefield',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=300',
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800'
    ],
    details: 'Independent House • Family Only',
    description: 'A spacious independent house in the quiet suburbs of Whitefield.',
    price: 28000,
    bedrooms: 2,
    furnished: true,
    category: 'homes',
    location: 'Whitefield, Bangalore',
    rating: 4.6,
    reviewCount: 67,
    badges: ['FAMILY ONLY'],
    offers: [],
    configuration: '2 BHK + 2 Bath',
    size: '1,200 sq. ft.',
    floor: 'Ground Floor',
    facing: 'North-East',
    amenities: [
      { icon: Flame, label: 'Garden' }
    ],
    owner: {
      name: 'Meera Reddy',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100',
      verified: true,
      activeSince: '1 month'
    }
  },
];

export const ALL_PROPERTIES: Property[] = [
  ...SIZZLING_DEALS,
  ...RECENTLY_VIEWED,
  {
    id: 'v1',
    title: 'Royal Villa with Private Pool',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800'],
    tag: 'EXCLUSIVE',
    details: '4 BHK • 5 Bath • 4,500 sq. ft.',
    description: 'A magnificent villa offering ultimate privacy and luxury.',
    price: 125000,
    bedrooms: 4,
    furnished: true,
    category: 'villas',
    location: 'Palm Meadows, Whitefield, Bangalore',
    rating: 4.9,
    reviewCount: 42,
    badges: ['PRIVATE POOL', 'LUXURY'],
    offers: ['Special Weekend Discount: 15% off'],
    configuration: '4 BHK + 5 Bath',
    size: '4,500 sq. ft.',
    floor: 'G + 2 Floors',
    facing: 'East',
    amenities: [{ icon: Waves, label: 'Pool' }, { icon: Dumbbell, label: 'Gym' }],
    owner: { name: 'Aditya Birla', image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '1 year' }
  },
  {
    id: 'v2',
    title: 'Mediterranean Style Villa',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800'],
    tag: 'HOT DEAL',
    details: '5 BHK • 6 Bath • 5,200 sq. ft.',
    description: 'Stunning Mediterranean architecture with modern interiors.',
    price: 185000,
    bedrooms: 5,
    furnished: true,
    category: 'villas',
    location: 'Sadashiva Nagar, Bangalore',
    rating: 4.8,
    reviewCount: 24,
    badges: ['PREMIUM', 'VERIFIED'],
    offers: [],
    configuration: '5 BHK',
    size: '5,200 sq. ft.',
    floor: 'G + 1',
    facing: 'North',
    amenities: [{ icon: Waves, label: 'Pool' }],
    owner: { name: 'Rajesh Khanna', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '2 years' }
  },
  {
    id: 'rm1',
    title: 'Cozy Single Room for Students',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800'],
    details: '1 Room • Shared Bath',
    description: 'Perfect for students looking for a quiet place to study.',
    price: 6500,
    bedrooms: 1,
    furnished: true,
    category: 'rooms',
    location: 'Near Christ University, Bangalore',
    rating: 4.1,
    reviewCount: 28,
    badges: ['STUDENT FRIENDLY'],
    offers: [],
    configuration: '1 Room',
    size: '150 sq. ft.',
    floor: '2nd Floor',
    facing: 'North',
    amenities: [{ icon: Zap, label: 'WiFi' }],
    owner: { name: 'Mrs. Gupta', image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '2 years' }
  },
  {
    id: 'rm2',
    title: 'Executive Room in MG Road',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    details: '1 Room • Attached Bath',
    description: 'Premium room for working professionals in the city center.',
    price: 15000,
    bedrooms: 1,
    furnished: true,
    category: 'rooms',
    location: 'MG Road, Bangalore',
    rating: 4.5,
    reviewCount: 42,
    badges: ['CITY CENTER', 'AC'],
    offers: [],
    configuration: '1 Room',
    size: '250 sq. ft.',
    floor: '5th Floor',
    facing: 'East',
    amenities: [{ icon: Zap, label: 'WiFi' }],
    owner: { name: 'Sanjay Dutt', image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '1 year' }
  },
  {
    id: 'h1',
    title: 'Modern 2BHK Independent House',
    image: 'https://images.unsplash.com/photo-1464890100898-a385f744067f?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1464890100898-a385f744067f?auto=format&fit=crop&q=80&w=800'],
    details: '2 BHK • 2 Bath • Garden',
    description: 'A beautiful independent house with a small garden in the front.',
    price: 22000,
    bedrooms: 2,
    furnished: false,
    category: 'homes',
    location: 'Jayanagar, Bangalore',
    rating: 4.4,
    reviewCount: 56,
    badges: ['GARDEN', 'PET FRIENDLY'],
    offers: [],
    configuration: '2 BHK',
    size: '1,100 sq. ft.',
    floor: 'Ground Floor',
    facing: 'West',
    amenities: [{ icon: Zap, label: 'Backup' }],
    owner: { name: 'Ramesh Babu', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '6 months' }
  },
  {
    id: 'h2',
    title: 'Spacious 3BHK Family Home',
    image: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&q=80&w=800'],
    details: '3 BHK • 3 Bath • Parking',
    description: 'Ideal for a large family, located in a peaceful residential area.',
    price: 35000,
    bedrooms: 3,
    furnished: true,
    category: 'homes',
    location: 'BTM Layout, Bangalore',
    rating: 4.3,
    reviewCount: 38,
    badges: ['FAMILY ONLY', 'QUIET AREA'],
    offers: [],
    configuration: '3 BHK',
    size: '1,800 sq. ft.',
    floor: 'G + 1',
    facing: 'South',
    amenities: [{ icon: Zap, label: 'Backup' }],
    owner: { name: 'Priya Mani', image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '3 years' }
  },
  {
    id: 'pg3',
    title: 'Stanza Living - Tokyo House',
    image: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=800'],
    details: 'Single Sharing • Premium',
    description: 'Modern PG with high-speed internet and professional housekeeping.',
    price: 18000,
    bedrooms: 1,
    furnished: true,
    category: 'pgs',
    location: 'Koramangala 4th Block, Bangalore',
    rating: 4.9,
    reviewCount: 156,
    badges: ['HIGH SPEED WIFI', 'CLEAN'],
    offers: [],
    configuration: 'Single Sharing',
    size: '300 sq. ft.',
    floor: '1st Floor',
    facing: 'North',
    amenities: [{ icon: Zap, label: 'WiFi' }, { icon: ShieldCheck, label: 'Security' }],
    owner: { name: 'Stanza Living', image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '4 years' }
  },
  {
    id: 'a3',
    title: 'Skyline View Apartment',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=400',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800'],
    details: '2 BHK • 2 Bath • Balcony',
    description: 'Beautiful apartment with a stunning view of the city skyline.',
    price: 32000,
    bedrooms: 2,
    furnished: true,
    category: 'apartments',
    location: 'Hebbal, Bangalore',
    rating: 4.6,
    reviewCount: 74,
    badges: ['SKYLINE VIEW', 'BALCONY'],
    offers: [],
    configuration: '2 BHK',
    size: '1,250 sq. ft.',
    floor: '15th Floor',
    facing: 'West',
    amenities: [{ icon: Zap, label: 'Backup' }, { icon: Dumbbell, label: 'Gym' }],
    owner: { name: 'Kiran Rao', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100', verified: true, activeSince: '1 year' }
  }
];
